- hosts: app
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Run App Container
      docker_container:
        name: myapp
        image: madhavkb/myapp:latest
        state: started
        ports:
          - "80:3000"